[package]
name = "strategy-price-arb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
config.workspace = true
core-types.workspace = true
strategy-traits.workspace = true
market-data.workspace = true
rust_decimal.workspace = true
serde.workspace = true
tracing.workspace = true

[dev-dependencies]
rust_decimal_macros.workspace = true
